# Generated by Django 2.0.7 on 2019-06-23 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Beginner', max_length=50)),
                ('description', models.CharField(default='Beginner', max_length=150)),
                ('category', models.CharField(default='Beginner', max_length=50)),
                ('chapter', models.PositiveIntegerField()),
                ('answer', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.PositiveIntegerField()),
                ('test_times', models.PositiveIntegerField(default=0)),
                ('test_total', models.PositiveIntegerField(default=0)),
                ('test_correct', models.PositiveIntegerField(default=0)),
                ('test_wrong', models.PositiveIntegerField(default=0)),
                ('test_success_rate', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Quiz'),
        ),
    ]
