# Generated by Django 2.0.7 on 2019-06-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(default='Syntax', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(default='Beginner', max_length=150),
        ),
    ]
