# Generated by Django 2.0.7 on 2019-06-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190623_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='test_correct',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='test_success_rate',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='test_times',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='test_total',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='test_wrong',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='user',
        ),
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
