# Generated by Django 2.0.7 on 2019-06-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_statisticspercategory_extra_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='extra_material',
            field=models.CharField(blank=True, default='https://www.google.com', help_text='This SHOULD be url link to extra studying material for the current chapter!', max_length=100),
        ),
    ]
