# Generated by Django 2.0.7 on 2019-06-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190623_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice_a',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_b',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_c',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_d',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ManyToManyField(to='courses.Quiz'),
        ),
    ]
