# Generated by Django 2.0.7 on 2019-06-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190623_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='chapter',
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(max_length=150),
        ),
    ]
