# Generated by Django 2.0.7 on 2019-06-30 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('level', models.CharField(default='Beginner', max_length=50)),
                ('rank', models.ImageField(default='ranks/Beginner.png', upload_to='')),
                ('attending_course', models.CharField(blank=True, default='Python 3: From zero to hero', max_length=100, null=True)),
                ('chapter_studying', models.PositiveIntegerField(default=1)),
                ('test_taking', models.PositiveIntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
