# Generated by Django 2.0.7 on 2019-06-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bad_at',
            field=models.CharField(default='', max_length=50),
        ),
    ]
