# Generated by Django 2.0.7 on 2019-06-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default='No bio.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='test_taking',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
