# Generated by Django 2.0.7 on 2019-06-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190623_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='attending_course',
            field=models.CharField(blank=True, default='Python 3: From zero to hero', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bad_at',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
