# Generated by Django 2.0.7 on 2019-06-23 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190623_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='section_studying',
            new_name='chapter_studying',
        ),
    ]
